services:
  mongodb:
    image: mongo:8
    container_name: mojuri-mongodb
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - mojuri_mongodb:/data/db

volumes:
  mojuri_mongodb:
