import { useState } from 'react';
import type { FormEvent } from 'react';
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query';
import { useParams } from 'react-router-dom';
import StoreLayout from '../components/StoreLayout';
import ProductCard from '../components/ProductCard';
import { api } from '../lib/api';
import { useCart } from '../store/CartContext';
import type { Product } from '../types';

export default function StoreProductDetail(){
  const{slug=''}=useParams();const{add}=useCart();const[image,setImage]=useState('');const[quantity,setQuantity]=useState(1);const queryClient=useQueryClient();
  const productQuery=useQuery({queryKey:['product',slug],queryFn:()=>api<Product>(`/products/${slug}`)});const product=productQuery.data;
  const relatedQuery=useQuery({queryKey:['products','related',product?.category],queryFn:()=>api<{items:Product[]}>(`/products?category=${encodeURIComponent(product!.category)}&limit=4`),enabled:Boolean(product)});
  const reviewMutation=useMutation({mutationFn:(body:Record<string,unknown>)=>api(`/products/${product!._id}/reviews`,{method:'POST',body:JSON.stringify(body)}),onSuccess:()=>queryClient.invalidateQueries({queryKey:['product',slug]})});
  function review(event:FormEvent<HTMLFormElement>){event.preventDefault();const element=event.currentTarget;const form=new FormData(element);reviewMutation.mutate({name:form.get('name'),email:form.get('email'),rating:Number(form.get('rating')),comment:form.get('comment')},{onSuccess:()=>element.reset()})}
  if(productQuery.error)return <StoreLayout><p className="store-error">{productQuery.error.message}</p></StoreLayout>;if(!product)return <StoreLayout><p className="store-loading">Loading jewelry…</p></StoreLayout>;
  const gallery=[product.thumbnail,...(product.gallery??[])].filter((value,index,list)=>list.indexOf(value)===index);const currentImage=image||product.thumbnail;const related=(relatedQuery.data?.items??[]).filter(x=>x._id!==product._id).slice(0,3);
  return <StoreLayout><main className="store-main"><section className="product-detail"><div><img className="product-gallery-main" src={currentImage} alt={product.name}/><div className="product-thumbs">{gallery.map(url=><img src={url} alt="Product view" onClick={()=>setImage(url)} key={url}/>)}</div></div><div className="product-info"><small>{product.category}</small><h1>{product.name}</h1><div className="stars">{'★'.repeat(Math.round(product.averageRating||0))}{'☆'.repeat(5-Math.round(product.averageRating||0))} <small>({product.reviews?.length??0} reviews)</small></div><div className="detail-price">{product.salePrice!=null&&<del>${product.price.toFixed(2)}</del>}<b>${(product.salePrice??product.price).toFixed(2)}</b></div><div className="product-description" dangerouslySetInnerHTML={{__html:product.description}}/><p className="stock-note">{product.stock?`${product.stock} in stock`:'Out of stock'}</p><div className="detail-buy"><input type="number" min="1" max={product.stock} value={quantity} onChange={e=>setQuantity(Number(e.target.value))}/><button className="store-button" disabled={!product.stock} onClick={()=>add(product,quantity)}>Add to bag</button></div></div></section><section className="review-layout"><div><h2>Customer reviews</h2>{product.reviews?.map(item=><article className="review" key={item._id}><div className="stars">{'★'.repeat(item.rating)}{'☆'.repeat(5-item.rating)}</div><b>{item.name}</b><p>{item.comment}</p></article>)}{!product.reviews?.length&&<p>No reviews yet.</p>}</div><form className="store-form" onSubmit={review}><h2>Write a review</h2><div className="store-form-row"><label>Name<input className="store-input" name="name" required/></label><label>Email<input className="store-input" name="email" type="email" required/></label></div><label>Rating<select className="store-select" name="rating" defaultValue="5"><option value="5">5 stars</option><option value="4">4 stars</option><option value="3">3 stars</option><option value="2">2 stars</option><option value="1">1 star</option></select></label><label>Review<textarea className="store-textarea" name="comment" required/></label><button className="store-button" disabled={reviewMutation.isPending}>Submit review</button>{reviewMutation.error&&<p className="store-error">{reviewMutation.error.message}</p>}</form></section>{related.length>0&&<section className="recent-posts"><div className="store-title"><small>You may also like</small><h1>Related jewelry</h1></div><div className="product-grid">{related.map(item=><ProductCard product={item} key={item._id}/>)}</div></section>}</main></StoreLayout>;
}
